
# tap repositories and their packages

tap homebrew/core
brew gdbm
brew ghq
brew git
brew glide
brew gmp
brew jq
brew mackup
brew mas
brew openssl
brew readline
brew tree
brew wget
brew xz
brew tmux
brew fzf
brew bash-completion

# brew berkeley-db
# brew go
# brew goenv
# brew mongodb
# brew open-cobol
# brew phplint
# brew python
# brew sqlite

tap homebrew/cask

tap argon/mas

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 1333542190 1Password 7 (7.2.1)
appstore 405843582 Alfred (1.2)
appstore 411246225 Caffeine (1.1.1)
appstore 777233759 Focus (5.0.3)
appstore 493949693 iMage Tools (1.0.16)
appstore 408981434 iMovie (10.1.9)
appstore 1273536147 IO (0.2.8)
appstore 408981381 iPhoto (9.6.1)
appstore 409183694 Keynote (8.2)
appstore 409203825 Numbers (5.2)
appstore 409201541 Pages (7.2)
appstore 425424353 The Unarchiver (4.0.0)
# appstore 682658836 GarageBand (10.3.1)
# appstore 748212890 Memory Cleaner (2.4.5)
# appstore 597419160 Sleep Pillow (1.0)
# appstore 909760813 Who's On My WiFi (1.1.2)
#appstore 497799835 Xcode (10.1)

# cask dropbox
# cask google-chrome

# 一旦コメントアウト
# cask docker
# cask visual-studio-code
# cask kindle

